import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const virgil = localFont({
  src: "./fonts/virgil.woff2",
  variable: "--font-virgil",
  display: "swap",
});

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://workina.cafe";

const title = "workina.cafe — community café work map";
const description =
  "Find community-checked cafés with reliable Wi-Fi, outlets, quiet seats, and laptop-friendly policies.";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title,
  description,
  applicationName: "workina.cafe",
  openGraph: {
    title,
    description,
    url: "/",
    siteName: "workina.cafe",
    locale: "en_US",
    type: "website",
    // og:image is generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
    // twitter:image is generated by src/app/twitter-image.tsx
  },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      className={`${geistSans.variable} ${geistMono.variable} ${virgil.variable}`}
      lang="en"
    >
      <body>{children}</body>
    </html>
  );
}
